### ISSUE TITLE
Distinct server names or routes to applications on UAT

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/jupiter#1724]
Distinct server names or routes to applications instead of port ‘x’ is Jupiter, port ‘y’ is avalon, etc. Personally, I find names easier to remember than numbers. If the applications are containerised, a reverse proxy could handle the routing. [Envoy](https://www.envoyproxy.io/) or [Traefik](https://containo.us/traefik/)?

Originally posted by @pgwillia in #1680 ([comment](https://github.com/ualbertalib/jupiter/issues/1680#issuecomment-646341599))

**Comment by pgwillia** [comment]
[nginx-proxy](https://github.com/nginx-proxy/nginx-proxy) looks to be another option. It can handle multiple [virtual hosts](https://github.com/nginx-proxy/nginx-proxy#multiple-hosts) and has thought about [SSL using let's encrypt](https://github.com/nginx-proxy/nginx-proxy#ssl-support-using-letsencrypt).  There's an example for what this could look like as a [docker-compose](https://github.com/nginx-proxy/nginx-proxy#docker-compose)

**Comment by pgwillia** [comment]
Here's an article which describes [Traefik](https://medium.com/trabe/map-subdomains-to-docker-containers-with-traefik-efd6aa66e073) where you add [Traefik labels](https://medium.com/trabe/map-subdomains-to-docker-containers-with-traefik-efd6aa66e073#095b)
```
version: "3"services:
  calibre:
    image: linuxserver/calibre-web
    container_name: calibre
    restart: unless-stopped
    ports:
      - "9083:8083"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cal.rule=Host(`books.mydomain.com`)"
      - "traefik.http.routers.cal.entrypoints=web"
      - "traefik.http.services.cal.loadbalancer.server.port=9083"
```
