### ISSUE TITLE
Setup Github Actions to run different versions of rubies

### ISSUE THREAD

**Issue by murny** [ualbertalib/jupiter#2081]
Docs on how to do this:
https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix

You can follow their example for NodeJS, just instead we going to do ruby for ourselves.

For us, just need to add the following right before `steps` ([on line 7 here]( https://github.com/ualbertalib/jupiter/blob/master/.github/workflows/push.yml#L7)) :
```
strategy:
      matrix:
        ruby: [ 2.6, 2.7, 3.0]
```

Then change the following:

```
      - name: Set up Ruby 2.6
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.6
```
to
```
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
```

This will generate 3 jobs for each ruby version we have specified.

Should be it to achieve this (with i'd imagine lots of testing)
