### ISSUE TITLE
Switch docker deployments to Postgresql

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/jupiter#465]
- Dockerfile update: Need to switch out `mysql-client` package for postgres equivalent (`postgresql-dev` i think?):
https://github.com/ualbertalib/jupiter/blob/master/Dockerfile#L9

- Docker-compose.yml (and other docker-compose.*.yml files) update: 
  - Update mysql section of file:
  https://github.com/ualbertalib/jupiter/blob/master/docker-compose.yml#L22-L27
  to basically something like:
  ```
  postgres:
    image: postgres:alpine (alpine if you want smaller container size)
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: jupiter
    volumes:
      - postgres:/var/lib/postgresql/data
  ```
  - Update DATABASE_URL to point to postgres now
  - Update image name from mysql to postgres everywhere (eg: depends_on)
